# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180112_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ebaylink',
            field=models.CharField(default='noproduct', max_length=999),
        ),
    ]
