# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180118_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
        ),
    ]
