# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
        ),
    ]
